import Image from 'next/image';
import {Footer, Header} from '../components';

export default function CirclesEvents(){return <main><Header dark/>
<section className="page-hero circles-page"><div className="reveal"><p className="eyebrow">Circles + events</p><h1>Gather from wherever life is happening.</h1><p>I create space to practice together, get quieter, stay curious, and reconnect in meaningful community.</p><div className="actions"><a className="button button-accent" href="#upcoming">Explore Circles + Events</a><a className="text-link" href="/private-events">Plan a Private Experience →</a></div></div><div className="page-hero-image image-reveal"><Image src="/images/cleanse.JPG" alt="A cleansing ritual at a community gathering" fill priority sizes="(max-width:800px) 100vw, 46vw"/></div></section>
<section className="circle-intro reveal"><span aria-hidden="true">✦</span><p className="eyebrow">A place to practice together</p><h2>Come curious. Leave a little more connected.</h2><p>My circles may include Reiki, chanting, meditation, prayer, spiritual teaching, reflection, crystals, or inner-child themes. The modality changes. The heart stays the same: stillness, discernment, devotion, self-trust, and honest connection.</p></section>
<section className="circle-types"><article><span>01</span><h3>Virtual Circles</h3><p>Guided practice, reflection, and community from home.</p></article><article><span>02</span><h3>Workshops</h3><p>Focused teaching and experiential practice around a meaningful theme.</p></article><article><span>03</span><h3>Sacred Gatherings</h3><p>Occasional in-person moments for presence, ritual, and connection.</p></article><article><span>04</span><h3>Collaborations + Retreats</h3><p>Thoughtful experiences created with aligned people and places.</p></article></section>
<section className="circle-gallery"><div className="wide image-reveal"><Image src="/images/community-event.JPG" alt="Zen supporting a participant in a community circle" fill sizes="65vw"/></div><div className="tall circle-symbol" aria-hidden="true"><Image src="/images/celestial-orbit.png" alt="" fill sizes="35vw"/><span>Gather<br/>in our<br/>own light.</span></div></section>
<section className="events-callout" id="upcoming"><div className="reveal"><p className="eyebrow">Circles + events</p><h2>See what’s opening next.</h2><p>I share new circles, workshops, and gathering details here as they open.</p><a className="button button-accent" href="#circle-signup">Join the Circles + Events List</a></div><aside><p>Planning a birthday, corporate gathering, private experience, collaboration, or retreat?</p><a className="text-link" href="/private-events">Plan a Private Experience →</a></aside></section>
<section className="community-signup" id="circle-signup"><div><p className="eyebrow">When the next circle opens</p><h2>Stay connected to the circle.</h2><p>I send announcements, reflections, workshops, and new offerings thoughtfully.</p></div><form action="https://YOUR-MAILERLITE-FORM-URL" method="post"><label className="sr-only" htmlFor="circle-email">Email address</label><input id="circle-email" name="email" type="email" placeholder="Email address" required/><button className="button" type="submit">Stay Connected</button></form></section>
<Footer/></main>}
