import Image from 'next/image';
import {Footer, Header} from '../components';
import {CrystalInquiryForm} from '../inquiry-form';

const etsy='https://www.etsy.com/shop/ShopSparkleLikeZen?etsrc=sdt';
const whatsapp='https://wa.me/17862018993?text=Hi%20Zen!%20I%E2%80%99d%20love%20help%20choosing%20a%20crystal.';

export default function Crystals(){return <main><Header dark/>
  <section className="crystals-hero"><div className="crystals-hero-image"><Image src="/images/crystal-vendor.JPG" alt="Zen with a colorful collection of crystals" fill priority sizes="(max-width:850px) 100vw, 54vw"/></div><div className="crystals-hero-copy reveal"><p className="eyebrow">Crystal experiences</p><h1>Choose with intention.</h1><p>Crystals can support a practice, mark a season, or simply bring beauty into a space. The power always remains within.</p><div className="actions"><a className="button button-accent" href={etsy}>Shop on Etsy</a><a className="text-link" href={whatsapp}>Request Crystal Guidance →</a></div></div></section>
  <section className="crystal-concierge"><Image className="crystal-art crystal-art-amethyst" src="/images/crystal-watercolor-amethyst.png" alt="" width={620} height={620}/><div className="reveal"><p className="eyebrow">Crystal Concierge</p><h2>Guidance that begins within.</h2><p>I start with what is present, not what is trending. From there, I offer practical education and thoughtful recommendations to help you choose crystals that support the practice you are already building.</p><ul><li>Personalized crystal guidance</li><li>Crystal education + workshops</li><li>Curated pieces + personal selections</li></ul><div className="actions"><a className="button button-accent" href="#crystal-inquiry">Ask Me for Crystal Guidance</a></div></div><div className="crystal-vendor-image image-reveal"><Image src="/images/crystal-grid.JPG" alt="A warm arrangement of crystals centered around a heart stone" fill sizes="(max-width:850px) 100vw, 48vw"/></div></section>
  <section className="crystal-detail"><div className="crystal-detail-image starfish-crystal image-reveal"><Image src="/images/starfish-crystal.jpg" alt="A golden starfish-shaped crystal resting in sunlit sand" fill sizes="(max-width:850px) calc(100vw - 48px), 42vw"/></div><div className="reveal"><p className="eyebrow">A personal selection</p><h2>Let curiosity lead.</h2><p>No one needs to know every name or meaning before beginning. I invite curiosity, better questions, and a thoughtful choice that will actually be used with care.</p><a className="button" href={etsy}>Explore the Etsy shop</a></div></section>
  <section className="crystal-inquiry" id="crystal-inquiry"><Image className="crystal-art crystal-art-jade" src="/images/crystal-watercolor-jade.png" alt="" width={560} height={560}/><div className="reveal"><p className="eyebrow">Crystal Concierge inquiry</p><h2>Tell me what you are drawn to.</h2><p>Share where you are and what you are looking for. I read every note and follow up personally.</p></div><CrystalInquiryForm/></section>
  <Footer/>
</main>}
