import Image from 'next/image';
import {Footer, Header} from './components';

const whatsapp='https://wa.me/17862018993?text=Hi%20Zen!%20I%20found%20you%20through%20the%20Sparkle%20Like%20Zen%20website%20and%20I%E2%80%99d%20love%20to%20learn%20more%20about%20working%20together.';
const animalWA='https://wa.me/17862018993?text=Hi%20Zen!%20I%E2%80%99d%20love%20to%20learn%20more%20about%20Reiki%20for%20my%20fur%20baby.';

export default function Home(){return <main className="immersive-home"><Header/>
  <section className="art-hero"><Image src="/images/theme-image.JPG" alt="A luminous garden landscape with a golden spiral" fill priority sizes="100vw"/><div className="art-hero-veil"/><div className="art-hero-copy reveal"><p className="eyebrow">Reflection · energetic support · integration</p><h1>Come home to inner knowing.</h1><p>I create personal spiritual experiences that quiet the noise, invite reconnection, and carry what is discovered into everyday life.</p><div className="actions"><a className="button button-accent" href="/private-work">Explore The Sparkle Experience</a><a className="button button-light" href="/circles-events">Circles + Events</a></div></div><p className="hero-whisper">The tools offer support. Inner knowing leads.</p></section>

  <section className="belief"><Image className="belief-orbit" src="/images/celestial-orbit.png" alt="" fill sizes="700px"/><div className="belief-copy reveal"><p className="eyebrow">The heart of the work</p><h2>We are<br/>the tool.</h2><p>The transformation comes first. Reiki, crystals, prayer, meditation, and reflection are tools I may draw from depending on the person and the moment. My goal is never dependence. It is more quiet, more connection, and deeper trust in personal discernment.</p></div></section>

  <section className="home-practice-pair"><div className="home-gong image-reveal"><Image src="/images/hero-gong.JPG" alt="Zen seated in front of a ceremonial gong" fill sizes="(max-width:850px) 100vw, 58vw"/></div><div className="home-reiki image-reveal"><Image src="/images/reiki.JPG" alt="Hands offering Reiki over a resting client’s eyes" fill sizes="(max-width:850px) 100vw, 42vw"/></div><p><b>Sound, stillness &amp; energetic support</b><span>Held with care.</span></p></section>

  <section className="signature"><Image className="signature-atmosphere" src="/images/celestial-orbit.png" alt="" fill sizes="100vw"/><div className="signature-copy reveal"><p className="eyebrow">My signature private session</p><h2>The Sparkle Experience</h2><p className="lede">I hold a private space to quiet the noise, reconnect, receive grounded spiritual support, and leave with something meaningful for everyday life.</p><div className="price-note"><b>Virtual · 60 minutes · $111</b><span>Mobile sessions are available by inquiry. Pricing varies by location and travel.</span></div><ol className="method"><li><b>Reflect</b><span>Start with what is actually present.</span></li><li><b>Receive</b><span>Rest into the practice that fits the moment.</span></li><li><b>Integrate</b><span>Make meaning of what surfaced.</span></li><li><b>Reconnect</b><span>Leave closer to inner knowing.</span></li></ol><div className="actions"><a className="button button-accent" href="/private-work#inquire">Book / Inquire</a><a className="text-link" href={whatsapp}>Text Me →</a></div></div></section>

  <section className="editorial-quote"><Image className="quote-celestial" src="/images/celestial-corner.png" alt="" fill sizes="900px"/><p className="eyebrow">A quiet truth</p><blockquote>“Intuition is calm knowing.”</blockquote><p>Become quiet enough to hear yourself.</p></section>

  <section className="world-paths"><div className="world-title reveal"><p className="eyebrow">Three ways to enter the world</p><h2>Start where you feel drawn.</h2></div><div className="world-grid"><article className="world-one"><div><span>01</span><h3>The Sparkle Experience</h3><p>Private spiritual support shaped around what is present for you.</p><a href="/private-work">Explore the experience →</a></div><Image src="/images/reiki -with-zen.JPG" alt="Zen supporting a private client" fill sizes="(max-width:850px) 100vw, 34vw"/></article><article className="world-two"><Image src="/images/cleanse.JPG" alt="Zen offering a feather cleansing ritual during a gathering" fill sizes="(max-width:850px) 100vw, 34vw"/><div><span>02</span><h3>Circles + Events</h3><p>Shared practice, warm community, and intentional gatherings.</p><a href="/circles-events">Gather with us →</a></div></article><article className="world-three"><div><span>03</span><h3>Crystal Experiences</h3><p>Personal guidance, education, and thoughtfully curated support.</p><a href="/crystals">Explore Crystal Experiences →</a></div><Image src="/images/crystals-outdoor.JPG" alt="Three crystal towers beside water" fill sizes="(max-width:850px) 100vw, 30vw"/></article></div></section>

  <section className="gather"><Image className="gather-atmosphere" src="/images/celestial-corner.png" alt="" fill sizes="100vw"/><div className="gather-copy reveal"><span className="gather-script">Gather in good company.</span><p className="eyebrow">Circles + events</p><h2>Gather from wherever life is happening.</h2><p>I create circles that may weave together meditation, energy work, chanting, prayer, reflection, teaching, crystals, and honest conversation.</p><div className="actions"><a className="button button-accent" href="/circles-events">Explore Circles + Events</a><a className="text-link" href="/private-events">Plan a Private Experience →</a></div></div></section>

  <section className="crystal-experience" id="crystals"><Image className="crystal-atmosphere" src="/images/celestial-orbit.png" alt="" fill sizes="100vw"/><div className="crystal-copy reveal"><p className="eyebrow">Crystal experiences</p><h2>Allies for your practice, not the source of your power.</h2><p>Crystal Concierge offers personal guidance, practical education, and thoughtfully curated pieces to support the practice you are already building.</p><ul><li>Personalized crystal guidance</li><li>Crystal education + workshops</li><li>Curated pieces + personal selections</li></ul><div className="actions"><a className="button" href="/crystals">Explore Crystal Experiences</a><a className="text-link" href="https://www.etsy.com/shop/ShopSparkleLikeZen?etsrc=sdt">Shop on Etsy ↗</a></div></div><span className="crystal-script">Choose with intention.</span></section>

  <section className="zen-and-pets"><article className="zen-intro"><div className="zen-photo"><Image src="/images/about-pic.JPG" alt="Zen smiling warmly" fill sizes="(max-width:850px) 100vw, 38vw"/></div><div><p className="eyebrow">Meet me</p><h2>Hi, I’m Zen.</h2><p>Life is always teaching me something, and I genuinely love learning. I’m always exploring new practices, asking questions, and finding ways to deepen what I know. Some of that is for me, and some becomes part of how I care for my clients and community. I listen first, then choose what might actually help.</p><a className="button" href="/about">Read My Story</a></div></article><article className="pet-support"><div><p className="eyebrow">A little extra love</p><h3>Healing for the fur babies.</h3><p>I offer gentle remote or mobile Reiki support where each animal already feels safe.</p><a className="text-link" href={animalWA}>Ask Me About Animal Reiki →</a></div><div className="pet-photo"><Image src="/images/dog-reiki.JPG" alt="A joyful spotted puppy in the grass" fill sizes="320px"/></div></article></section>

  <section className="closing" id="contact"><div className="closing-copy reveal"><p className="eyebrow">Begin here</p><h2>No outside voice gets to define what is already known within.</h2><p>Sometimes a little quiet is all it takes to hear clearly.</p><div className="actions"><a className="button button-accent" href="#inquiry-form">Begin an Inquiry</a><a className="button button-light" href={whatsapp}>Text Me on WhatsApp</a></div></div><form id="inquiry-form" action="https://formspree.io/f/YOUR_FORM_ID" method="post"><label>Name<input name="name" required/></label><label>Email<input name="email" type="email" required/></label><label>Phone / WhatsApp<input name="phone" type="tel"/></label><label>What kind of support feels most relevant?<input name="support"/></label><label>Virtual or mobile?<select name="format"><option>Virtual</option><option>Mobile</option><option>Not sure yet</option></select></label><label>Preferred contact method<select name="preferred_contact"><option>WhatsApp</option><option>Email</option><option>Phone</option></select></label><label>Message<textarea name="message" rows={4} required/></label><button className="button button-accent" type="submit">Send Inquiry</button></form></section>
  <Footer/>
</main>}
