import Image from 'next/image';
import {Footer, Header} from './components';

export default function Home() { return <main>
  <Header/>
  <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">Spiritual self-trust · sacred connection</p><h1>A sacred space to reconnect with your own knowing.</h1><p className="hero-intro">Reiki, spiritual practice, reflection, and community—held with warmth, curiosity, and room to hear yourself clearly.</p><div className="actions"><a className="button" href="/private-work">Explore Private Work</a><a className="text-link" href="#circles">Upcoming Circles <span aria-hidden="true">↗</span></a></div></div><figure className="hero-image"><Image src="/images/hero-gong.JPG" alt="Zen seated peacefully in front of a large gong" fill priority sizes="(max-width: 800px) 100vw, 52vw"/><figcaption>A little quieter. A little closer to what’s true.</figcaption></figure></section>
  <section className="philosophy" id="philosophy"><span className="sun" aria-hidden="true">✦</span><p className="eyebrow">The heart of this work</p><h2>You are the tool.</h2><p>Crystals, Reiki, prayer, and spiritual practice can be beautiful supports. But they aren’t here to replace your own wisdom. The goal is to help you listen more deeply, trust your discernment, and walk away more connected to yourself and the Divine.</p></section>
  <section className="pathways" id="work"><div className="section-heading"><p className="eyebrow">Ways to work together</p><h2>Come as you are.<br/>We’ll begin there.</h2></div><div className="path-grid">
    <article className="path path-private"><div className="path-image"><Image src="/images/reiki-treatment.JPG" alt="A peaceful private Reiki treatment" fill sizes="(max-width:800px) 100vw, 42vw"/></div><span>01</span><h3>Private Experiences</h3><p>A deeply personal space to slow down, listen, and reconnect—through sacred reflection, Reiki, prayer, and practices chosen for you.</p><a href="/private-work">Explore private work →</a></article>
    <article className="path path-circle"><div className="path-image"><Image src="/images/community-event.JPG" alt="Zen offering Reiki during a community gathering" fill sizes="(max-width:800px) 100vw, 35vw"/></div><span>02</span><h3>Circles + Community</h3><p>Spaces to practice being present together. Chanting, meditation, prayer, teaching, and honest spiritual conversation.</p><a href="#circles">Find a circle →</a></article>
    <article className="path path-crystal"><div className="path-image"><Image src="/images/crystals-outdoor.JPG" alt="Three crystal towers outside near water" fill sizes="(max-width:800px) 100vw, 30vw"/></div><span>03</span><h3>Crystals + Sacred Tools</h3><p>One-of-a-kind stones and thoughtful education that help you deepen your practice—without giving your power away.</p><a href="#crystals">Meet the crystals →</a></article>
  </div></section>
  <section className="private-feature"><div className="private-photo"><Image src="/images/reiki -with-zen.JPG" alt="Zen offering a quiet, grounded Reiki session" fill sizes="(max-width:800px) 100vw, 48vw"/></div><div className="feature-copy"><p className="eyebrow">Private work</p><h2>Go deeper than a single session.</h2><p>There isn’t one formula for coming home to yourself. Our work can blend listening, sacred reflection, Reiki, prayer, meditation, and crystal support when it feels useful—not because a modality is the answer, but because it can help you hear your answer.</p><p>I may share intuitive impressions when they naturally arise. More importantly, we’ll create simple integration practices that can live with you long after our time together.</p><a className="button" href="/private-work">Explore Private Sessions</a><aside>Something deeper is taking shape here—a future signature journey for people ready to stay with the work.</aside></div></section>
  <section className="circles" id="circles"><div className="circles-copy"><p className="eyebrow">Circles + community</p><h2>Practice, presence, and a place to belong.</h2><p>Virtual circles are coming for people who want to explore discernment, trust, stillness, boundaries, self-acceptance, devotion, surrender, and sacred connection—without pretending we have it all figured out.</p><div className="mini-list"><span>Chanting</span><span>Meditation</span><span>Prayer</span><span>Teaching</span><span>Reflection</span></div><div className="actions"><a className="button" href="#contact">See Upcoming Circles</a><a className="text-link" href="#community">Join the WhatsApp Channel ↗</a></div></div><div className="circles-photo"><Image src="/images/cleanse.JPG" alt="A sacred community ritual held outdoors" fill sizes="(max-width:800px) 100vw, 44vw"/></div></section>
  <section className="quote-break"><span aria-hidden="true">☾</span><blockquote>“Intuition is calm knowing.”</blockquote><p>Become quiet enough to hear yourself.</p></section>
  <section className="crystals" id="crystals"><div className="crystal-collage"><div className="crystal-main"><Image src="/images/crystal-vendor.JPG" alt="Zen smiling behind a collection of crystals" fill sizes="(max-width:800px) 100vw, 44vw"/></div><div className="crystal-small"><Image src="/images/crystal-grid.JPG" alt="A warm-toned crystal grid" fill sizes="250px"/></div></div><div className="feature-copy"><p className="eyebrow">Crystals + sacred tools</p><h2>Allies for your practice, not the source of your power.</h2><p>Shop one-of-a-kind crystals, minerals, and vintage crystal jewelry—or let me help you find something deeply personal through Crystal Concierge.</p><ul><li>Crystal Concierge + consultations</li><li>Education + guided meditations</li><li>Event crystal bar experiences</li><li>Small, intentional Etsy drops</li></ul><div className="actions"><a className="button" href="#">Shop the Collection</a><a className="text-link" href="#contact">Explore Crystal Concierge →</a></div></div></section>
  <section className="animal"><div><p className="eyebrow">A little extra love</p><h2>Healing for the fur babies.</h2><p>Gentle Reiki support for the animals who make our lives better. Available remotely or as a mobile session, so they can stay somewhere they already feel safe.</p><a className="text-link" href="#contact">Ask about animal Reiki →</a></div><div className="animal-photo"><Image src="/images/dog-reiki.JPG" alt="A joyful spotted puppy lying in green grass" fill sizes="(max-width:800px) 100vw, 40vw"/></div></section>
  <section className="meet" id="about"><div className="meet-photo"><Image src="/images/about-pic.JPG" alt="A warm portrait of Zen smiling" fill sizes="(max-width:800px) 100vw, 43vw"/></div><div className="feature-copy"><p className="eyebrow">Meet your guide</p><h2>Hi, I’m Zen.</h2><p>I love creating spaces where people can slow down, get quiet, and reconnect with themselves. I’m a big believer in listening before “doing,” and in letting spiritual experiences become part of real, ordinary life.</p><p>I’m not here to tell you what every sign means. I want to help you build enough trust in yourself to begin discerning that for yourself. My own path is moving deeper into Vedic mysticism while staying in conversation with Catholic mystical traditions, prayer, and sacred ritual.</p><a className="button" href="/about">Read My Story</a></div></section>
  <section className="community" id="community"><div><p className="eyebrow">Notes from Zen</p><h2>Stay connected.</h2><p>Circle announcements, workshops, reflections, crystal drops, and new offerings—sent thoughtfully, never constantly.</p></div><form action="https://YOUR-MAILERLITE-FORM-URL" method="post"><label className="sr-only" htmlFor="signup-email">Email address</label><input id="signup-email" name="email" type="email" placeholder="Your email address" required/><button className="button" type="submit">Join the List</button></form><a className="whatsapp" href="#">Prefer WhatsApp? Join the broadcast channel ↗</a></section>
  <section className="final-cta" id="contact"><div><span aria-hidden="true">✦</span><h2>You don’t need another person to tell you who you are.</h2><p>Sometimes you need a space quiet enough to remember.</p><div className="actions"><a className="button" href="/private-work">Work With Zen</a><a className="text-link" href="#circles">Explore Upcoming Events →</a></div></div><form action="https://formspree.io/f/YOUR_FORM_ID" method="post"><p className="eyebrow">Send a note</p><label>Name<input name="name" required/></label><label>Email<input name="email" type="email" required/></label><label>What are you interested in?<select name="interest"><option>Private work</option><option>Circles + events</option><option>Crystal Concierge</option><option>Animal Reiki</option><option>Something else</option></select></label><label>Tell me a little about what’s calling you<textarea name="message" rows={4} required/></label><button className="button" type="submit">Send Inquiry</button></form></section>
  <Footer/>
  </main> }
