import Image from 'next/image';
import {Footer, Header} from '../components';
import {InquiryForm} from '../inquiry-form';
import {ReflectionsSlider} from '../reflections-slider';
import {CalendlyBookingButton, CalendlyInlineBooking} from '../calendly-booking';

export default function InnerTemple(){return <main><Header dark/><section className="page-hero sparkle-page"><div className="reveal"><p className="eyebrow">My signature private session</p><h1>The Inner Temple</h1><p>Space to listen, reflect, receive, and reconnect.</p><div className="session-price"><b>Virtual · 60 minutes · $111</b><span>Mobile available by inquiry. Pricing varies by location and travel.</span></div><div className="actions"><CalendlyBookingButton>Book Your Session</CalendlyBookingButton><a className="text-link" href="#questions">Have a Question? →</a></div></div><div className="page-hero-image image-reveal"><Image src="/images/reiki-treatment.JPG" alt="Zen supporting a client during The Inner Temple" fill priority sizes="(max-width:850px) 100vw, 48vw"/></div></section>
<section className="session-intro reveal"><p className="eyebrow">A session shaped around what is present</p><h2>We begin with what is here.</h2><p>This is not a Reiki menu or a one-size-fits-all ritual. I listen first. From there, I may draw from reflection, energetic support, prayer, meditation, crystals, or another practice that genuinely fits the moment.</p></section>
<section className="experience-flow"><article><span>01</span><h3>Reflect</h3><p>Start with what is actually present, without rushing to explain it away.</p></article><i/><article><span>02</span><h3>Receive</h3><p>Allow room for rest, prayer, energetic support, or the practice that fits.</p></article><i/><article><span>03</span><h3>Integrate</h3><p>Make meaning of what surfaced and name something practical to carry forward.</p></article><i/><article><span>04</span><h3>Reconnect</h3><p>Leave closer to your own knowing, not dependent on someone else’s interpretation.</p></article></section>
<ReflectionsSlider intro={{eyebrow:'Client reflections',title:'In their words.',link:{href:'/client-reflections',label:'Read all reflections →'}}}/>
<section className="process"><div className="process-photo image-reveal"><Image src="/images/crystal-grid-on-woman.JPG" alt="Crystals placed thoughtfully during a private experience" fill sizes="(max-width:850px) 100vw, 46vw"/></div><div className="reveal"><p className="eyebrow">What you can expect</p><h2>A quiet hour with somewhere to land.</h2><p>You do not need to arrive with the right words or know which tool you need. Bring what you are carrying. Together, we make room to hear it and close with something useful for real life.</p><blockquote>“I want our work together to strengthen your own intuition, discernment, and ability to recognize what you need, so that each session leaves you feeling more connected to your own inner guidance.”</blockquote></div></section>
<section className="inner-temple-booking" id="book-inner-temple"><div className="booking-intro"><p className="eyebrow">Ready when you are</p><h2>Book your Inner Temple session</h2><p>Choose a time that feels right for you and complete your booking below.</p></div><CalendlyInlineBooking/></section>
<section className="inquiry inquiry-vertical inquiry-questions" id="questions"><div className="reveal"><p className="eyebrow">Have a question?</p><h2>Not sure yet? Reach out.</h2><p>If you have a question about The Inner Temple or want to make sure it feels like the right fit, send me a note and I’ll be happy to help.</p></div><InquiryForm/></section><Footer/></main>}
